INSERT INTO tag (id, tag_name) VALUES
(NULL, '3D printing'),
(NULL, 'Acting'),
(NULL, 'Aeromodeling'),
(NULL, 'Air sports'),
(NULL, 'Airbrushing'),
(NULL, 'Aircraft Spotting'),
(NULL, 'Airsoft'),
(NULL, 'Airsofting'),
(NULL, 'Amateur astronomy'),
(NULL, 'Amateur geology'),
(NULL, 'Amateur Radio'),
(NULL, 'American football'),
(NULL, 'Animal fancy'),
(NULL, 'Animals/pets/dogs'),
(NULL, 'Antiquing'),
(NULL, 'Antiquities'),
(NULL, 'Aqua-lung'),
(NULL, 'Aquarium (Freshwater & Saltwater)'),
(NULL, 'Archery'),
(NULL, 'Art collecting'),
(NULL, 'Arts'),
(NULL, 'Association football'),
(NULL, 'Astrology'),
(NULL, 'Astronomy'),
(NULL, 'Audiophilia'),
(NULL, 'Australian rules football'),
(NULL, 'Auto audiophilia'),
(NULL, 'Auto racing'),
(NULL, 'Backgammon'),
(NULL, 'Backpacking'),
(NULL, 'Badminton'),
(NULL, 'Base Jumping'),
(NULL, 'Baseball'),
(NULL, 'Basketball'),
(NULL, 'Baton Twirling'),
(NULL, 'Beach Volleyball'),
(NULL, 'Beach/Sun tanning'),
(NULL, 'Beachcombing'),
(NULL, 'Beadwork'),
(NULL, 'Beatboxing'),
(NULL, 'Becoming A Child Advocate'),
(NULL, 'Beekeeping'),
(NULL, 'Bell Ringing'),
(NULL, 'Belly Dancing'),
(NULL, 'Bicycle Polo'),
(NULL, 'Bicycling'),
(NULL, 'Billiards'),
(NULL, 'Bird watching'),
(NULL, 'Birding'),
(NULL, 'Birdwatching'),
(NULL, 'Blacksmithing'),
(NULL, 'Blogging'),
(NULL, 'BMX'),
(NULL, 'Board games'),
(NULL, 'Board sports'),
(NULL, 'BoardGames'),
(NULL, 'Boating'),
(NULL, 'Body Building'),
(NULL, 'Bodybuilding'),
(NULL, 'Bonsai Tree'),
(NULL, 'Book collecting'),
(NULL, 'Bookbinding'),
(NULL, 'Boomerangs'),
(NULL, 'Bowling'),
(NULL, 'Boxing'),
(NULL, 'Brazilian jiu-jitsu'),
(NULL, 'Breakdancing'),
(NULL, 'Brewing Beer'),
(NULL, 'Bridge'),
(NULL, 'Bridge Building'),
(NULL, 'Bringing Food To The Disabled'),
(NULL, 'Building A House For Habitat For Humanity'),
(NULL, 'Building Dollhouses'),
(NULL, 'Bus spotting'),
(NULL, 'Butterfly Watching'),
(NULL, 'Button Collecting'),
(NULL, 'Cake Decorating'),
(NULL, 'Calligraphy'),
(NULL, 'Camping'),
(NULL, 'Candle making'),
(NULL, 'Canoeing'),
(NULL, 'Car Racing'),
(NULL, 'Card collecting'),
(NULL, 'Cartooning'),
(NULL, 'Casino Gambling'),
(NULL, 'Cave Diving'),
(NULL, 'Ceramics'),
(NULL, 'Cheerleading'),
(NULL, 'Chess'),
(NULL, 'Church/church activities'),
(NULL, 'Cigar Smoking'),
(NULL, 'Climbing'),
(NULL, 'Cloud Watching'),
(NULL, 'Coin Collecting'),
(NULL, 'Collecting'),
(NULL, 'Collecting Antiques'),
(NULL, 'Collecting Artwork'),
(NULL, 'Collecting Hats'),
(NULL, 'Collecting Music Albums'),
(NULL, 'Collecting RPM Records'),
(NULL, 'Collecting Sports Cards (Baseball, Football, Basketball, Hockey)'),
(NULL, 'Collecting Swords'),
(NULL, 'Color guard'),
(NULL, 'Coloring'),
(NULL, 'Comic book collecting'),
(NULL, 'Compose Music'),
(NULL, 'Computer activities'),
(NULL, 'Computer programming'),
(NULL, 'Conworlding'),
(NULL, 'Cooking'),
(NULL, 'Cosplay'),
(NULL, 'Cosplaying'),
(NULL, 'Couponing'),
(NULL, 'Crafts'),
(NULL, 'Crafts (unspecified)'),
(NULL, 'Creative writing'),
(NULL, 'Cricket'),
(NULL, 'Crochet'),
(NULL, 'Crocheting'),
(NULL, 'Cross-Stitch'),
(NULL, 'Crossword Puzzles'),
(NULL, 'Cryptography'),
(NULL, 'Curling'),
(NULL, 'Cycling'),
(NULL, 'Dance'),
(NULL, 'Dancing'),
(NULL, 'Darts'),
(NULL, 'Debate'),
(NULL, 'Deltiology (postcard collecting)'),
(NULL, 'Diecast Collectibles'),
(NULL, 'Digital arts'),
(NULL, 'Digital Photography'),
(NULL, 'Disc golf'),
(NULL, 'Do it yourself'),
(NULL, 'Dodgeball'),
(NULL, 'Dog sport'),
(NULL, 'Dolls'),
(NULL, 'Dominoes'),
(NULL, 'Dowsing'),
(NULL, 'Drama'),
(NULL, 'Drawing'),
(NULL, 'Driving'),
(NULL, 'Dumpster Diving'),
(NULL, 'Eating out'),
(NULL, 'Educational Courses'),
(NULL, 'Electronics'),
(NULL, 'Element collecting'),
(NULL, 'Embroidery'),
(NULL, 'Entertaining'),
(NULL, 'Equestrianism'),
(NULL, 'Exercise (aerobics, weights)'),
(NULL, 'Exhibition drill'),
(NULL, 'Falconry'),
(NULL, 'Fast cars'),
(NULL, 'Felting'),
(NULL, 'Fencing'),
(NULL, 'Field hockey'),
(NULL, 'Figure skating'),
(NULL, 'Fire Poi'),
(NULL, 'Fishing'),
(NULL, 'Fishkeeping'),
(NULL, 'Flag Football'),
(NULL, 'Floorball'),
(NULL, 'Floral Arrangements'),
(NULL, 'Flower arranging'),
(NULL, 'Flower collecting and pressing'),
(NULL, 'Fly Tying'),
(NULL, 'Flying'),
(NULL, 'Footbag'),
(NULL, 'Football'),
(NULL, 'Foraging'),
(NULL, 'Foreign language learning'),
(NULL, 'Fossil hunting'),
(NULL, 'Four Wheeling'),
(NULL, 'Freshwater Aquariums'),
(NULL, 'Frisbee Golf – Frolf'),
(NULL, 'Gambling'),
(NULL, 'Games'),
(NULL, 'Gaming (tabletop games and role-playing games)'),
(NULL, 'Garage Saleing'),
(NULL, 'Gardening'),
(NULL, 'Genealogy'),
(NULL, 'Geocaching'),
(NULL, 'Ghost hunting'),
(NULL, 'Glassblowing'),
(NULL, 'Glowsticking'),
(NULL, 'Gnoming'),
(NULL, 'Go'),
(NULL, 'Go Kart Racing'),
(NULL, 'Going to movies'),
(NULL, 'Golf'),
(NULL, 'Golfing'),
(NULL, 'Gongoozling'),
(NULL, 'Graffiti'),
(NULL, 'Grip Strength'),
(NULL, 'Guitar'),
(NULL, 'Gun Collecting'),
(NULL, 'Gunsmithing'),
(NULL, 'Gymnastics'),
(NULL, 'Gyotaku'),
(NULL, 'Handball'),
(NULL, 'Handwriting Analysis'),
(NULL, 'Hang gliding'),
(NULL, 'Herping'),
(NULL, 'Hiking'),
(NULL, 'Home Brewing'),
(NULL, 'Home Repair'),
(NULL, 'Home Theater'),
(NULL, 'Homebrewing'),
(NULL, 'Hooping'),
(NULL, 'Horse riding'),
(NULL, 'Hot air ballooning'),
(NULL, 'Hula Hooping'),
(NULL, 'Hunting'),
(NULL, 'Ice hockey'),
(NULL, 'Ice skating'),
(NULL, 'Iceskating'),
(NULL, 'Illusion'),
(NULL, 'Impersonations'),
(NULL, 'Inline skating'),
(NULL, 'Insect collecting'),
(NULL, 'Internet'),
(NULL, 'Inventing'),
(NULL, 'Jet Engines'),
(NULL, 'Jewelry Making'),
(NULL, 'Jigsaw Puzzles'),
(NULL, 'Jogging'),
(NULL, 'Judo'),
(NULL, 'Juggling'),
(NULL, 'Jukskei'),
(NULL, 'Jump Roping'),
(NULL, 'Kabaddi'),
(NULL, 'Kart racing'),
(NULL, 'Kayaking'),
(NULL, 'Keep A Journal'),
(NULL, 'Kitchen Chemistry'),
(NULL, 'Kite Boarding'),
(NULL, 'Kite flying'),
(NULL, 'Kites'),
(NULL, 'Kitesurfing'),
(NULL, 'Knapping'),
(NULL, 'Knife making'),
(NULL, 'Knife throwing'),
(NULL, 'Knitting'),
(NULL, 'Knotting'),
(NULL, 'Lacemaking'),
(NULL, 'Lacrosse'),
(NULL, 'Lapidary'),
(NULL, 'LARPing'),
(NULL, 'Laser tag'),
(NULL, 'Lasers'),
(NULL, 'Lawn Darts'),
(NULL, 'Learn to Play Poker'),
(NULL, 'Learning A Foreign Language'),
(NULL, 'Learning An Instrument'),
(NULL, 'Learning To Pilot A Plane'),
(NULL, 'Leather crafting'),
(NULL, 'Leathercrafting'),
(NULL, 'Lego building'),
(NULL, 'Legos'),
(NULL, 'Letterboxing'),
(NULL, 'Listening to music'),
(NULL, 'Locksport'),
(NULL, 'Machining'),
(NULL, 'Macramé'),
(NULL, 'Magic'),
(NULL, 'Mahjong'),
(NULL, 'Making Model Cars'),
(NULL, 'Marbles'),
(NULL, 'Marksmanship'),
(NULL, 'Martial arts'),
(NULL, 'Matchstick Modeling'),
(NULL, 'Meditation'),
(NULL, 'Metal detecting'),
(NULL, 'Meteorology'),
(NULL, 'Microscopy'),
(NULL, 'Mineral collecting'),
(NULL, 'Model aircraft'),
(NULL, 'Model building'),
(NULL, 'Model Railroading'),
(NULL, 'Model Rockets'),
(NULL, 'Modeling Ships'),
(NULL, 'Models'),
(NULL, 'Motor sports'),
(NULL, 'Motorcycles'),
(NULL, 'Mountain Biking'),
(NULL, 'Mountain Climbing'),
(NULL, 'Mountaineering'),
(NULL, 'Movie and movie memorabilia collecting'),
(NULL, 'Mushroom hunting/Mycology'),
(NULL, 'Musical Instruments'),
(NULL, 'Nail Art'),
(NULL, 'Needlepoint'),
(NULL, 'Netball'),
(NULL, 'Nordic skating'),
(NULL, 'Orienteering'),
(NULL, 'Origami'),
(NULL, 'Owning An Antique Car'),
(NULL, 'Paintball'),
(NULL, 'Painting'),
(NULL, 'Papermache'),
(NULL, 'Papermaking'),
(NULL, 'Parachuting'),
(NULL, 'Paragliding or Power Paragliding'),
(NULL, 'Parkour'),
(NULL, 'People Watching'),
(NULL, 'Photography'),
(NULL, 'Piano'),
(NULL, 'Pigeon racing'),
(NULL, 'Pinochle'),
(NULL, 'Pipe Smoking'),
(NULL, 'Planking'),
(NULL, 'Playing music'),
(NULL, 'Playing musical instruments'),
(NULL, 'Playing team sports'),
(NULL, 'Poker'),
(NULL, 'Pole Dancing'),
(NULL, 'Polo'),
(NULL, 'Pottery'),
(NULL, 'Powerboking'),
(NULL, 'Protesting'),
(NULL, 'Puppetry'),
(NULL, 'Puzzles'),
(NULL, 'Pyrotechnics'),
(NULL, 'Quilting'),
(NULL, 'R/C Boats'),
(NULL, 'R/C Cars'),
(NULL, 'R/C Helicopters'),
(NULL, 'R/C Planes'),
(NULL, 'Racing Pigeons'),
(NULL, 'Racquetball'),
(NULL, 'Radio-controlled car racing'),
(NULL, 'Rafting'),
(NULL, 'Railfans'),
(NULL, 'Rappelling'),
(NULL, 'Rapping'),
(NULL, 'Reading'),
(NULL, 'Reading To The Elderly'),
(NULL, 'Record collecting'),
(NULL, 'Relaxing'),
(NULL, 'Renaissance Faire'),
(NULL, 'Renting movies'),
(NULL, 'Rescuing Abused Or Abandoned Animals'),
(NULL, 'Robotics'),
(NULL, 'Rock balancing'),
(NULL, 'Rock climbing'),
(NULL, 'Rock Collecting'),
(NULL, 'Rockets'),
(NULL, 'Rocking AIDS Babies'),
(NULL, 'Roleplaying'),
(NULL, 'Roller derby'),
(NULL, 'Roller skating'),
(NULL, 'Rugby'),
(NULL, 'Rugby league football'),
(NULL, 'Running'),
(NULL, 'Sailing'),
(NULL, 'Saltwater Aquariums'),
(NULL, 'Sand art'),
(NULL, 'Sand Castles'),
(NULL, 'Scrapbooking'),
(NULL, 'Scuba diving'),
(NULL, 'Sculling or Rowing'),
(NULL, 'Sculpting'),
(NULL, 'Sea glass collecting'),
(NULL, 'Seashell collecting'),
(NULL, 'Self Defense'),
(NULL, 'Sewing'),
(NULL, 'Shark Fishing'),
(NULL, 'Shooting'),
(NULL, 'Shooting sport'),
(NULL, 'Shopping'),
(NULL, 'Shortwave listening'),
(NULL, 'Singing'),
(NULL, 'Singing In Choir'),
(NULL, 'Skateboarding'),
(NULL, 'Skeet Shooting'),
(NULL, 'Sketching'),
(NULL, 'Skiing'),
(NULL, 'Skimboarding'),
(NULL, 'Sky Diving'),
(NULL, 'Skydiving'),
(NULL, 'Slack Lining'),
(NULL, 'Slacklining'),
(NULL, 'Sleeping'),
(NULL, 'Slingshots'),
(NULL, 'Slot car racing'),
(NULL, 'Snorkeling'),
(NULL, 'Snowboarding'),
(NULL, 'Soap Making'),
(NULL, 'Soapmaking'),
(NULL, 'Soccer'),
(NULL, 'Socializing with friends/neighbors'),
(NULL, 'Speed Cubing (rubix cube)'),
(NULL, 'Speed skating'),
(NULL, 'Spelunkering'),
(NULL, 'Spending time with family/kids'),
(NULL, 'Sports'),
(NULL, 'Squash'),
(NULL, 'Stamp Collecting'),
(NULL, 'Stand-up comedy'),
(NULL, 'Stone collecting'),
(NULL, 'Stone skipping'),
(NULL, 'Storm Chasing'),
(NULL, 'Storytelling'),
(NULL, 'String Figures'),
(NULL, 'Sudoku'),
(NULL, 'Surf Fishing'),
(NULL, 'Surfing'),
(NULL, 'Survival'),
(NULL, 'Swimming'),
(NULL, 'Table football'),
(NULL, 'Table tennis'),
(NULL, 'Taekwondo'),
(NULL, 'Tai chi'),
(NULL, 'Tatting'),
(NULL, 'Taxidermy'),
(NULL, 'Tea Tasting'),
(NULL, 'Tennis'),
(NULL, 'Tesla Coils'),
(NULL, 'Tetris'),
(NULL, 'Textiles'),
(NULL, 'Texting'),
(NULL, 'Tombstone Rubbing'),
(NULL, 'Tool Collecting'),
(NULL, 'Tour skating'),
(NULL, 'Toy Collecting'),
(NULL, 'Train Collecting'),
(NULL, 'Train Spotting'),
(NULL, 'Trainspotting'),
(NULL, 'Traveling'),
(NULL, 'Treasure Hunting'),
(NULL, 'Trekkie'),
(NULL, 'Triathlon'),
(NULL, 'Tutoring Children'),
(NULL, 'TV watching'),
(NULL, 'Ultimate Frisbee'),
(NULL, 'Urban exploration'),
(NULL, 'Vehicle restoration'),
(NULL, 'Video game collecting'),
(NULL, 'Video Games'),
(NULL, 'Video gaming'),
(NULL, 'Videophilia'),
(NULL, 'Vintage cars'),
(NULL, 'Violin'),
(NULL, 'Volleyball'),
(NULL, 'Volunteer'),
(NULL, 'Walking'),
(NULL, 'Warhammer'),
(NULL, 'Watching movies'),
(NULL, 'Watching sporting events'),
(NULL, 'Water sports'),
(NULL, 'Weather Watcher'),
(NULL, 'Web surfing'),
(NULL, 'Weightlifting'),
(NULL, 'Windsurfing'),
(NULL, 'Wine Making'),
(NULL, 'Wingsuit Flying'),
(NULL, 'Wood carving'),
(NULL, 'Woodworking'),
(NULL, 'Working In A Food Pantry'),
(NULL, 'Working on cars'),
(NULL, 'World Record Breaking'),
(NULL, 'Worldbuilding'),
(NULL, 'Wrestling'),
(NULL, 'Writing'),
(NULL, 'Writing Music'),
(NULL, 'Writing Songs'),
(NULL, 'Yo-yoing'),
(NULL, 'Yoga'),
(NULL, 'YoYo'),
(NULL, 'Ziplining'),
(NULL, 'Zumba');
