insert into tag (id, tag_name) values (NULL, '3D printing');
insert into tag (id, tag_name) values (NULL, 'Acting');
insert into tag (id, tag_name) values (NULL, 'Aeromodeling');
insert into tag (id, tag_name) values (NULL, 'Air sports');
insert into tag (id, tag_name) values (NULL, 'Airbrushing');
insert into tag (id, tag_name) values (NULL, 'Aircraft Spotting');
insert into tag (id, tag_name) values (NULL, 'Airsoft');
insert into tag (id, tag_name) values (NULL, 'Airsofting');
insert into tag (id, tag_name) values (NULL, 'Amateur astronomy');
insert into tag (id, tag_name) values (NULL, 'Amateur geology');
insert into tag (id, tag_name) values (NULL, 'Amateur Radio');
insert into tag (id, tag_name) values (NULL, 'American football');
insert into tag (id, tag_name) values (NULL, 'Animal fancy');
insert into tag (id, tag_name) values (NULL, 'Animals/pets/dogs');
insert into tag (id, tag_name) values (NULL, 'Antiquing');
insert into tag (id, tag_name) values (NULL, 'Antiquities');
insert into tag (id, tag_name) values (NULL, 'Aqua-lung');
insert into tag (id, tag_name) values (NULL, 'Aquarium (Freshwater & Saltwater)');
insert into tag (id, tag_name) values (NULL, 'Archery');
insert into tag (id, tag_name) values (NULL, 'Art collecting');
insert into tag (id, tag_name) values (NULL, 'Arts');
insert into tag (id, tag_name) values (NULL, 'Association football');
insert into tag (id, tag_name) values (NULL, 'Astrology');
insert into tag (id, tag_name) values (NULL, 'Astronomy');
insert into tag (id, tag_name) values (NULL, 'Audiophilia');
insert into tag (id, tag_name) values (NULL, 'Australian rules football');
insert into tag (id, tag_name) values (NULL, 'Auto audiophilia');
insert into tag (id, tag_name) values (NULL, 'Auto racing');
insert into tag (id, tag_name) values (NULL, 'Backgammon');
insert into tag (id, tag_name) values (NULL, 'Backpacking');
insert into tag (id, tag_name) values (NULL, 'Badminton');
insert into tag (id, tag_name) values (NULL, 'Base Jumping');
insert into tag (id, tag_name) values (NULL, 'Baseball');
insert into tag (id, tag_name) values (NULL, 'Basketball');
insert into tag (id, tag_name) values (NULL, 'Baton Twirling');
insert into tag (id, tag_name) values (NULL, 'Beach Volleyball');
insert into tag (id, tag_name) values (NULL, 'Beach/Sun tanning');
insert into tag (id, tag_name) values (NULL, 'Beachcombing');
insert into tag (id, tag_name) values (NULL, 'Beadwork');
insert into tag (id, tag_name) values (NULL, 'Beatboxing');
insert into tag (id, tag_name) values (NULL, 'Becoming A Child Advocate');
insert into tag (id, tag_name) values (NULL, 'Beekeeping');
insert into tag (id, tag_name) values (NULL, 'Bell Ringing');
insert into tag (id, tag_name) values (NULL, 'Belly Dancing');
insert into tag (id, tag_name) values (NULL, 'Bicycle Polo');
insert into tag (id, tag_name) values (NULL, 'Bicycling');
insert into tag (id, tag_name) values (NULL, 'Billiards');
insert into tag (id, tag_name) values (NULL, 'Bird watching');
insert into tag (id, tag_name) values (NULL, 'Birding');
insert into tag (id, tag_name) values (NULL, 'Birdwatching');
insert into tag (id, tag_name) values (NULL, 'Blacksmithing');
insert into tag (id, tag_name) values (NULL, 'Blogging');
insert into tag (id, tag_name) values (NULL, 'BMX');
insert into tag (id, tag_name) values (NULL, 'Board games');
insert into tag (id, tag_name) values (NULL, 'Board sports');
insert into tag (id, tag_name) values (NULL, 'BoardGames');
insert into tag (id, tag_name) values (NULL, 'Boating');
insert into tag (id, tag_name) values (NULL, 'Body Building');
insert into tag (id, tag_name) values (NULL, 'Bodybuilding');
insert into tag (id, tag_name) values (NULL, 'Bonsai Tree');
insert into tag (id, tag_name) values (NULL, 'Book collecting');
insert into tag (id, tag_name) values (NULL, 'Bookbinding');
insert into tag (id, tag_name) values (NULL, 'Boomerangs');
insert into tag (id, tag_name) values (NULL, 'Bowling');
insert into tag (id, tag_name) values (NULL, 'Boxing');
insert into tag (id, tag_name) values (NULL, 'Brazilian jiu-jitsu');
insert into tag (id, tag_name) values (NULL, 'Breakdancing');
insert into tag (id, tag_name) values (NULL, 'Brewing Beer');
insert into tag (id, tag_name) values (NULL, 'Bridge');
insert into tag (id, tag_name) values (NULL, 'Bridge Building');
insert into tag (id, tag_name) values (NULL, 'Bringing Food To The Disabled');
insert into tag (id, tag_name) values (NULL, 'Building A House For Habitat For Humanity');
insert into tag (id, tag_name) values (NULL, 'Building Dollhouses');
insert into tag (id, tag_name) values (NULL, 'Bus spotting');
insert into tag (id, tag_name) values (NULL, 'Butterfly Watching');
insert into tag (id, tag_name) values (NULL, 'Button Collecting');
insert into tag (id, tag_name) values (NULL, 'Cake Decorating');
insert into tag (id, tag_name) values (NULL, 'Calligraphy');
insert into tag (id, tag_name) values (NULL, 'Camping');
insert into tag (id, tag_name) values (NULL, 'Candle making');
insert into tag (id, tag_name) values (NULL, 'Canoeing');
insert into tag (id, tag_name) values (NULL, 'Car Racing');
insert into tag (id, tag_name) values (NULL, 'Card collecting');
insert into tag (id, tag_name) values (NULL, 'Cartooning');
insert into tag (id, tag_name) values (NULL, 'Casino Gambling');
insert into tag (id, tag_name) values (NULL, 'Cave Diving');
insert into tag (id, tag_name) values (NULL, 'Ceramics');
insert into tag (id, tag_name) values (NULL, 'Cheerleading');
insert into tag (id, tag_name) values (NULL, 'Chess');
insert into tag (id, tag_name) values (NULL, 'Church/church activities');
insert into tag (id, tag_name) values (NULL, 'Cigar Smoking');
insert into tag (id, tag_name) values (NULL, 'Climbing');
insert into tag (id, tag_name) values (NULL, 'Cloud Watching');
insert into tag (id, tag_name) values (NULL, 'Coin Collecting');
insert into tag (id, tag_name) values (NULL, 'Collecting');
insert into tag (id, tag_name) values (NULL, 'Collecting Antiques');
insert into tag (id, tag_name) values (NULL, 'Collecting Artwork');
insert into tag (id, tag_name) values (NULL, 'Collecting Hats');
insert into tag (id, tag_name) values (NULL, 'Collecting Music Albums');
insert into tag (id, tag_name) values (NULL, 'Collecting RPM Records');
insert into tag (id, tag_name) values (NULL, 'Collecting Sports Cards (Baseball, Football, Basketball, Hockey)');
insert into tag (id, tag_name) values (NULL, 'Collecting Swords');
insert into tag (id, tag_name) values (NULL, 'Color guard');
insert into tag (id, tag_name) values (NULL, 'Coloring');
insert into tag (id, tag_name) values (NULL, 'Comic book collecting');
insert into tag (id, tag_name) values (NULL, 'Compose Music');
insert into tag (id, tag_name) values (NULL, 'Computer activities');
insert into tag (id, tag_name) values (NULL, 'Computer programming');
insert into tag (id, tag_name) values (NULL, 'Conworlding');
insert into tag (id, tag_name) values (NULL, 'Cooking');
insert into tag (id, tag_name) values (NULL, 'Cosplay');
insert into tag (id, tag_name) values (NULL, 'Cosplaying');
insert into tag (id, tag_name) values (NULL, 'Couponing');
insert into tag (id, tag_name) values (NULL, 'Crafts');
insert into tag (id, tag_name) values (NULL, 'Crafts (unspecified)');
insert into tag (id, tag_name) values (NULL, 'Creative writing');
insert into tag (id, tag_name) values (NULL, 'Cricket');
insert into tag (id, tag_name) values (NULL, 'Crochet');
insert into tag (id, tag_name) values (NULL, 'Crocheting');
insert into tag (id, tag_name) values (NULL, 'Cross-Stitch');
insert into tag (id, tag_name) values (NULL, 'Crossword Puzzles');
insert into tag (id, tag_name) values (NULL, 'Cryptography');
insert into tag (id, tag_name) values (NULL, 'Curling');
insert into tag (id, tag_name) values (NULL, 'Cycling');
insert into tag (id, tag_name) values (NULL, 'Dance');
insert into tag (id, tag_name) values (NULL, 'Dancing');
insert into tag (id, tag_name) values (NULL, 'Darts');
insert into tag (id, tag_name) values (NULL, 'Debate');
insert into tag (id, tag_name) values (NULL, 'Deltiology (postcard collecting)');
insert into tag (id, tag_name) values (NULL, 'Diecast Collectibles');
insert into tag (id, tag_name) values (NULL, 'Digital arts');
insert into tag (id, tag_name) values (NULL, 'Digital Photography');
insert into tag (id, tag_name) values (NULL, 'Disc golf');
insert into tag (id, tag_name) values (NULL, 'Do it yourself');
insert into tag (id, tag_name) values (NULL, 'Dodgeball');
insert into tag (id, tag_name) values (NULL, 'Dog sport');
insert into tag (id, tag_name) values (NULL, 'Dolls');
insert into tag (id, tag_name) values (NULL, 'Dominoes');
insert into tag (id, tag_name) values (NULL, 'Dowsing');
insert into tag (id, tag_name) values (NULL, 'Drama');
insert into tag (id, tag_name) values (NULL, 'Drawing');
insert into tag (id, tag_name) values (NULL, 'Driving');
insert into tag (id, tag_name) values (NULL, 'Dumpster Diving');
insert into tag (id, tag_name) values (NULL, 'Eating out');
insert into tag (id, tag_name) values (NULL, 'Educational Courses');
insert into tag (id, tag_name) values (NULL, 'Electronics');
insert into tag (id, tag_name) values (NULL, 'Element collecting');
insert into tag (id, tag_name) values (NULL, 'Embroidery');
insert into tag (id, tag_name) values (NULL, 'Entertaining');
insert into tag (id, tag_name) values (NULL, 'Equestrianism');
insert into tag (id, tag_name) values (NULL, 'Exercise (aerobics, weights)');
insert into tag (id, tag_name) values (NULL, 'Exhibition drill');
insert into tag (id, tag_name) values (NULL, 'Falconry');
insert into tag (id, tag_name) values (NULL, 'Fast cars');
insert into tag (id, tag_name) values (NULL, 'Felting');
insert into tag (id, tag_name) values (NULL, 'Fencing');
insert into tag (id, tag_name) values (NULL, 'Field hockey');
insert into tag (id, tag_name) values (NULL, 'Figure skating');
insert into tag (id, tag_name) values (NULL, 'Fire Poi');
insert into tag (id, tag_name) values (NULL, 'Fishing');
insert into tag (id, tag_name) values (NULL, 'Fishkeeping');
insert into tag (id, tag_name) values (NULL, 'Flag Football');
insert into tag (id, tag_name) values (NULL, 'Floorball');
insert into tag (id, tag_name) values (NULL, 'Floral Arrangements');
insert into tag (id, tag_name) values (NULL, 'Flower arranging');
insert into tag (id, tag_name) values (NULL, 'Flower collecting and pressing');
insert into tag (id, tag_name) values (NULL, 'Fly Tying');
insert into tag (id, tag_name) values (NULL, 'Flying');
insert into tag (id, tag_name) values (NULL, 'Footbag');
insert into tag (id, tag_name) values (NULL, 'Football');
insert into tag (id, tag_name) values (NULL, 'Foraging');
insert into tag (id, tag_name) values (NULL, 'Foreign language learning');
insert into tag (id, tag_name) values (NULL, 'Fossil hunting');
insert into tag (id, tag_name) values (NULL, 'Four Wheeling');
insert into tag (id, tag_name) values (NULL, 'Freshwater Aquariums');
insert into tag (id, tag_name) values (NULL, 'Frisbee Golf – Frolf');
insert into tag (id, tag_name) values (NULL, 'Gambling');
insert into tag (id, tag_name) values (NULL, 'Games');
insert into tag (id, tag_name) values (NULL, 'Gaming (tabletop games and role-playing games)');
insert into tag (id, tag_name) values (NULL, 'Garage Saleing');
insert into tag (id, tag_name) values (NULL, 'Gardening');
insert into tag (id, tag_name) values (NULL, 'Genealogy');
insert into tag (id, tag_name) values (NULL, 'Geocaching');
insert into tag (id, tag_name) values (NULL, 'Ghost hunting');
insert into tag (id, tag_name) values (NULL, 'Glassblowing');
insert into tag (id, tag_name) values (NULL, 'Glowsticking');
insert into tag (id, tag_name) values (NULL, 'Gnoming');
insert into tag (id, tag_name) values (NULL, 'Go');
insert into tag (id, tag_name) values (NULL, 'Go Kart Racing');
insert into tag (id, tag_name) values (NULL, 'Going to movies');
insert into tag (id, tag_name) values (NULL, 'Golf');
insert into tag (id, tag_name) values (NULL, 'Golfing');
insert into tag (id, tag_name) values (NULL, 'Gongoozling');
insert into tag (id, tag_name) values (NULL, 'Graffiti');
insert into tag (id, tag_name) values (NULL, 'Grip Strength');
insert into tag (id, tag_name) values (NULL, 'Guitar');
insert into tag (id, tag_name) values (NULL, 'Gun Collecting');
insert into tag (id, tag_name) values (NULL, 'Gunsmithing');
insert into tag (id, tag_name) values (NULL, 'Gymnastics');
insert into tag (id, tag_name) values (NULL, 'Gyotaku');
insert into tag (id, tag_name) values (NULL, 'Handball');
insert into tag (id, tag_name) values (NULL, 'Handwriting Analysis');
insert into tag (id, tag_name) values (NULL, 'Hang gliding');
insert into tag (id, tag_name) values (NULL, 'Herping');
insert into tag (id, tag_name) values (NULL, 'Hiking');
insert into tag (id, tag_name) values (NULL, 'Home Brewing');
insert into tag (id, tag_name) values (NULL, 'Home Repair');
insert into tag (id, tag_name) values (NULL, 'Home Theater');
insert into tag (id, tag_name) values (NULL, 'Homebrewing');
insert into tag (id, tag_name) values (NULL, 'Hooping');
insert into tag (id, tag_name) values (NULL, 'Horse riding');
insert into tag (id, tag_name) values (NULL, 'Hot air ballooning');
insert into tag (id, tag_name) values (NULL, 'Hula Hooping');
insert into tag (id, tag_name) values (NULL, 'Hunting');
insert into tag (id, tag_name) values (NULL, 'Ice hockey');
insert into tag (id, tag_name) values (NULL, 'Ice skating');
insert into tag (id, tag_name) values (NULL, 'Iceskating');
insert into tag (id, tag_name) values (NULL, 'Illusion');
insert into tag (id, tag_name) values (NULL, 'Impersonations');
insert into tag (id, tag_name) values (NULL, 'Inline skating');
insert into tag (id, tag_name) values (NULL, 'Insect collecting');
insert into tag (id, tag_name) values (NULL, 'Internet');
insert into tag (id, tag_name) values (NULL, 'Inventing');
insert into tag (id, tag_name) values (NULL, 'Jet Engines');
insert into tag (id, tag_name) values (NULL, 'Jewelry Making');
insert into tag (id, tag_name) values (NULL, 'Jigsaw Puzzles');
insert into tag (id, tag_name) values (NULL, 'Jogging');
insert into tag (id, tag_name) values (NULL, 'Judo');
insert into tag (id, tag_name) values (NULL, 'Juggling');
insert into tag (id, tag_name) values (NULL, 'Jukskei');
insert into tag (id, tag_name) values (NULL, 'Jump Roping');
insert into tag (id, tag_name) values (NULL, 'Kabaddi');
insert into tag (id, tag_name) values (NULL, 'Kart racing');
insert into tag (id, tag_name) values (NULL, 'Kayaking');
insert into tag (id, tag_name) values (NULL, 'Keep A Journal');
insert into tag (id, tag_name) values (NULL, 'Kitchen Chemistry');
insert into tag (id, tag_name) values (NULL, 'Kite Boarding');
insert into tag (id, tag_name) values (NULL, 'Kite flying');
insert into tag (id, tag_name) values (NULL, 'Kites');
insert into tag (id, tag_name) values (NULL, 'Kitesurfing');
insert into tag (id, tag_name) values (NULL, 'Knapping');
insert into tag (id, tag_name) values (NULL, 'Knife making');
insert into tag (id, tag_name) values (NULL, 'Knife throwing');
insert into tag (id, tag_name) values (NULL, 'Knitting');
insert into tag (id, tag_name) values (NULL, 'Knotting');
insert into tag (id, tag_name) values (NULL, 'Lacemaking');
insert into tag (id, tag_name) values (NULL, 'Lacrosse');
insert into tag (id, tag_name) values (NULL, 'Lapidary');
insert into tag (id, tag_name) values (NULL, 'LARPing');
insert into tag (id, tag_name) values (NULL, 'Laser tag');
insert into tag (id, tag_name) values (NULL, 'Lasers');
insert into tag (id, tag_name) values (NULL, 'Lawn Darts');
insert into tag (id, tag_name) values (NULL, 'Learn to Play Poker');
insert into tag (id, tag_name) values (NULL, 'Learning A Foreign Language');
insert into tag (id, tag_name) values (NULL, 'Learning An Instrument');
insert into tag (id, tag_name) values (NULL, 'Learning To Pilot A Plane');
insert into tag (id, tag_name) values (NULL, 'Leather crafting');
insert into tag (id, tag_name) values (NULL, 'Leathercrafting');
insert into tag (id, tag_name) values (NULL, 'Lego building');
insert into tag (id, tag_name) values (NULL, 'Legos');
insert into tag (id, tag_name) values (NULL, 'Letterboxing');
insert into tag (id, tag_name) values (NULL, 'Listening to music');
insert into tag (id, tag_name) values (NULL, 'Locksport');
insert into tag (id, tag_name) values (NULL, 'Machining');
insert into tag (id, tag_name) values (NULL, 'Macramé');
insert into tag (id, tag_name) values (NULL, 'Macrame');
insert into tag (id, tag_name) values (NULL, 'Magic');
insert into tag (id, tag_name) values (NULL, 'Mahjong');
insert into tag (id, tag_name) values (NULL, 'Making Model Cars');
insert into tag (id, tag_name) values (NULL, 'Marbles');
insert into tag (id, tag_name) values (NULL, 'Marksmanship');
insert into tag (id, tag_name) values (NULL, 'Martial arts');
insert into tag (id, tag_name) values (NULL, 'Matchstick Modeling');
insert into tag (id, tag_name) values (NULL, 'Meditation');
insert into tag (id, tag_name) values (NULL, 'Metal detecting');
insert into tag (id, tag_name) values (NULL, 'Meteorology');
insert into tag (id, tag_name) values (NULL, 'Microscopy');
insert into tag (id, tag_name) values (NULL, 'Mineral collecting');
insert into tag (id, tag_name) values (NULL, 'Model aircraft');
insert into tag (id, tag_name) values (NULL, 'Model building');
insert into tag (id, tag_name) values (NULL, 'Model Railroading');
insert into tag (id, tag_name) values (NULL, 'Model Rockets');
insert into tag (id, tag_name) values (NULL, 'Modeling Ships');
insert into tag (id, tag_name) values (NULL, 'Models');
insert into tag (id, tag_name) values (NULL, 'Motor sports');
insert into tag (id, tag_name) values (NULL, 'Motorcycles');
insert into tag (id, tag_name) values (NULL, 'Mountain Biking');
insert into tag (id, tag_name) values (NULL, 'Mountain Climbing');
insert into tag (id, tag_name) values (NULL, 'Mountaineering');
insert into tag (id, tag_name) values (NULL, 'Movie and movie memorabilia collecting');
insert into tag (id, tag_name) values (NULL, 'Mushroom hunting/Mycology');
insert into tag (id, tag_name) values (NULL, 'Musical Instruments');
insert into tag (id, tag_name) values (NULL, 'Nail Art');
insert into tag (id, tag_name) values (NULL, 'Needlepoint');
insert into tag (id, tag_name) values (NULL, 'Netball');
insert into tag (id, tag_name) values (NULL, 'Nordic skating');
insert into tag (id, tag_name) values (NULL, 'Orienteering');
insert into tag (id, tag_name) values (NULL, 'Origami');
insert into tag (id, tag_name) values (NULL, 'Owning An Antique Car');
insert into tag (id, tag_name) values (NULL, 'Paintball');
insert into tag (id, tag_name) values (NULL, 'Painting');
insert into tag (id, tag_name) values (NULL, 'Papermache');
insert into tag (id, tag_name) values (NULL, 'Papermaking');
insert into tag (id, tag_name) values (NULL, 'Parachuting');
insert into tag (id, tag_name) values (NULL, 'Paragliding or Power Paragliding');
insert into tag (id, tag_name) values (NULL, 'Parkour');
insert into tag (id, tag_name) values (NULL, 'People Watching');
insert into tag (id, tag_name) values (NULL, 'Photography');
insert into tag (id, tag_name) values (NULL, 'Piano');
insert into tag (id, tag_name) values (NULL, 'Pigeon racing');
insert into tag (id, tag_name) values (NULL, 'Pinochle');
insert into tag (id, tag_name) values (NULL, 'Pipe Smoking');
insert into tag (id, tag_name) values (NULL, 'Planking');
insert into tag (id, tag_name) values (NULL, 'Playing music');
insert into tag (id, tag_name) values (NULL, 'Playing musical instruments');
insert into tag (id, tag_name) values (NULL, 'Playing team sports');
insert into tag (id, tag_name) values (NULL, 'Poker');
insert into tag (id, tag_name) values (NULL, 'Pole Dancing');
insert into tag (id, tag_name) values (NULL, 'Polo');
insert into tag (id, tag_name) values (NULL, 'Pottery');
insert into tag (id, tag_name) values (NULL, 'Powerboking');
insert into tag (id, tag_name) values (NULL, 'Protesting');
insert into tag (id, tag_name) values (NULL, 'Puppetry');
insert into tag (id, tag_name) values (NULL, 'Puzzles');
insert into tag (id, tag_name) values (NULL, 'Pyrotechnics');
insert into tag (id, tag_name) values (NULL, 'Quilting');
insert into tag (id, tag_name) values (NULL, 'R/C Boats');
insert into tag (id, tag_name) values (NULL, 'R/C Cars');
insert into tag (id, tag_name) values (NULL, 'R/C Helicopters');
insert into tag (id, tag_name) values (NULL, 'R/C Planes');
insert into tag (id, tag_name) values (NULL, 'Racing Pigeons');
insert into tag (id, tag_name) values (NULL, 'Racquetball');
insert into tag (id, tag_name) values (NULL, 'Radio-controlled car racing');
insert into tag (id, tag_name) values (NULL, 'Rafting');
insert into tag (id, tag_name) values (NULL, 'Railfans');
insert into tag (id, tag_name) values (NULL, 'Rappelling');
insert into tag (id, tag_name) values (NULL, 'Rapping');
insert into tag (id, tag_name) values (NULL, 'Reading');
insert into tag (id, tag_name) values (NULL, 'Reading To The Elderly');
insert into tag (id, tag_name) values (NULL, 'Record collecting');
insert into tag (id, tag_name) values (NULL, 'Relaxing');
insert into tag (id, tag_name) values (NULL, 'Renaissance Faire');
insert into tag (id, tag_name) values (NULL, 'Renting movies');
insert into tag (id, tag_name) values (NULL, 'Rescuing Abused Or Abandoned Animals');
insert into tag (id, tag_name) values (NULL, 'Robotics');
insert into tag (id, tag_name) values (NULL, 'Rock balancing');
insert into tag (id, tag_name) values (NULL, 'Rock climbing');
insert into tag (id, tag_name) values (NULL, 'Rock Collecting');
insert into tag (id, tag_name) values (NULL, 'Rockets');
insert into tag (id, tag_name) values (NULL, 'Rocking AIDS Babies');
insert into tag (id, tag_name) values (NULL, 'Roleplaying');
insert into tag (id, tag_name) values (NULL, 'Roller derby');
insert into tag (id, tag_name) values (NULL, 'Roller skating');
insert into tag (id, tag_name) values (NULL, 'Rugby');
insert into tag (id, tag_name) values (NULL, 'Rugby league football');
insert into tag (id, tag_name) values (NULL, 'Running');
insert into tag (id, tag_name) values (NULL, 'Sailing');
insert into tag (id, tag_name) values (NULL, 'Saltwater Aquariums');
insert into tag (id, tag_name) values (NULL, 'Sand art');
insert into tag (id, tag_name) values (NULL, 'Sand Castles');
insert into tag (id, tag_name) values (NULL, 'Scrapbooking');
insert into tag (id, tag_name) values (NULL, 'Scuba diving');
insert into tag (id, tag_name) values (NULL, 'Sculling or Rowing');
insert into tag (id, tag_name) values (NULL, 'Sculpting');
insert into tag (id, tag_name) values (NULL, 'Sea glass collecting');
insert into tag (id, tag_name) values (NULL, 'Seashell collecting');
insert into tag (id, tag_name) values (NULL, 'Self Defense');
insert into tag (id, tag_name) values (NULL, 'Sewing');
insert into tag (id, tag_name) values (NULL, 'Shark Fishing');
insert into tag (id, tag_name) values (NULL, 'Shooting');
insert into tag (id, tag_name) values (NULL, 'Shooting sport');
insert into tag (id, tag_name) values (NULL, 'Shopping');
insert into tag (id, tag_name) values (NULL, 'Shortwave listening');
insert into tag (id, tag_name) values (NULL, 'Singing');
insert into tag (id, tag_name) values (NULL, 'Singing In Choir');
insert into tag (id, tag_name) values (NULL, 'Skateboarding');
insert into tag (id, tag_name) values (NULL, 'Skeet Shooting');
insert into tag (id, tag_name) values (NULL, 'Sketching');
insert into tag (id, tag_name) values (NULL, 'Skiing');
insert into tag (id, tag_name) values (NULL, 'Skimboarding');
insert into tag (id, tag_name) values (NULL, 'Sky Diving');
insert into tag (id, tag_name) values (NULL, 'Skydiving');
insert into tag (id, tag_name) values (NULL, 'Slack Lining');
insert into tag (id, tag_name) values (NULL, 'Slacklining');
insert into tag (id, tag_name) values (NULL, 'Sleeping');
insert into tag (id, tag_name) values (NULL, 'Slingshots');
insert into tag (id, tag_name) values (NULL, 'Slot car racing');
insert into tag (id, tag_name) values (NULL, 'Snorkeling');
insert into tag (id, tag_name) values (NULL, 'Snowboarding');
insert into tag (id, tag_name) values (NULL, 'Soap Making');
insert into tag (id, tag_name) values (NULL, 'Soapmaking');
insert into tag (id, tag_name) values (NULL, 'Soccer');
insert into tag (id, tag_name) values (NULL, 'Socializing with friends/neighbors');
insert into tag (id, tag_name) values (NULL, 'Speed Cubing (rubix cube)');
insert into tag (id, tag_name) values (NULL, 'Speed skating');
insert into tag (id, tag_name) values (NULL, 'Spelunkering');
insert into tag (id, tag_name) values (NULL, 'Spending time with family/kids');
insert into tag (id, tag_name) values (NULL, 'Sports');
insert into tag (id, tag_name) values (NULL, 'Squash');
insert into tag (id, tag_name) values (NULL, 'Stamp Collecting');
insert into tag (id, tag_name) values (NULL, 'Stand-up comedy');
insert into tag (id, tag_name) values (NULL, 'Stone collecting');
insert into tag (id, tag_name) values (NULL, 'Stone skipping');
insert into tag (id, tag_name) values (NULL, 'Storm Chasing');
insert into tag (id, tag_name) values (NULL, 'Storytelling');
insert into tag (id, tag_name) values (NULL, 'String Figures');
insert into tag (id, tag_name) values (NULL, 'Sudoku');
insert into tag (id, tag_name) values (NULL, 'Surf Fishing');
insert into tag (id, tag_name) values (NULL, 'Surfing');
insert into tag (id, tag_name) values (NULL, 'Survival');
insert into tag (id, tag_name) values (NULL, 'Swimming');
insert into tag (id, tag_name) values (NULL, 'Table football');
insert into tag (id, tag_name) values (NULL, 'Table tennis');
insert into tag (id, tag_name) values (NULL, 'Taekwondo');
insert into tag (id, tag_name) values (NULL, 'Tai chi');
insert into tag (id, tag_name) values (NULL, 'Tatting');
insert into tag (id, tag_name) values (NULL, 'Taxidermy');
insert into tag (id, tag_name) values (NULL, 'Tea Tasting');
insert into tag (id, tag_name) values (NULL, 'Tennis');
insert into tag (id, tag_name) values (NULL, 'Tesla Coils');
insert into tag (id, tag_name) values (NULL, 'Tetris');
insert into tag (id, tag_name) values (NULL, 'Textiles');
insert into tag (id, tag_name) values (NULL, 'Texting');
insert into tag (id, tag_name) values (NULL, 'Tombstone Rubbing');
insert into tag (id, tag_name) values (NULL, 'Tool Collecting');
insert into tag (id, tag_name) values (NULL, 'Tour skating');
insert into tag (id, tag_name) values (NULL, 'Toy Collecting');
insert into tag (id, tag_name) values (NULL, 'Train Collecting');
insert into tag (id, tag_name) values (NULL, 'Train Spotting');
insert into tag (id, tag_name) values (NULL, 'Trainspotting');
insert into tag (id, tag_name) values (NULL, 'Traveling');
insert into tag (id, tag_name) values (NULL, 'Treasure Hunting');
insert into tag (id, tag_name) values (NULL, 'Trekkie');
insert into tag (id, tag_name) values (NULL, 'Triathlon');
insert into tag (id, tag_name) values (NULL, 'Tutoring Children');
insert into tag (id, tag_name) values (NULL, 'TV watching');
insert into tag (id, tag_name) values (NULL, 'Ultimate Frisbee');
insert into tag (id, tag_name) values (NULL, 'Urban exploration');
insert into tag (id, tag_name) values (NULL, 'Vehicle restoration');
insert into tag (id, tag_name) values (NULL, 'Video game collecting');
insert into tag (id, tag_name) values (NULL, 'Video Games');
insert into tag (id, tag_name) values (NULL, 'Video gaming');
insert into tag (id, tag_name) values (NULL, 'Videophilia');
insert into tag (id, tag_name) values (NULL, 'Vintage cars');
insert into tag (id, tag_name) values (NULL, 'Violin');
insert into tag (id, tag_name) values (NULL, 'Volleyball');
insert into tag (id, tag_name) values (NULL, 'Volunteer');
insert into tag (id, tag_name) values (NULL, 'Walking');
insert into tag (id, tag_name) values (NULL, 'Warhammer');
insert into tag (id, tag_name) values (NULL, 'Watching movies');
insert into tag (id, tag_name) values (NULL, 'Watching sporting events');
insert into tag (id, tag_name) values (NULL, 'Water sports');
insert into tag (id, tag_name) values (NULL, 'Weather Watcher');
insert into tag (id, tag_name) values (NULL, 'Web surfing');
insert into tag (id, tag_name) values (NULL, 'Weightlifting');
insert into tag (id, tag_name) values (NULL, 'Windsurfing');
insert into tag (id, tag_name) values (NULL, 'Wine Making');
insert into tag (id, tag_name) values (NULL, 'Wingsuit Flying');
insert into tag (id, tag_name) values (NULL, 'Wood carving');
insert into tag (id, tag_name) values (NULL, 'Woodworking');
insert into tag (id, tag_name) values (NULL, 'Working In A Food Pantry');
insert into tag (id, tag_name) values (NULL, 'Working on cars');
insert into tag (id, tag_name) values (NULL, 'World Record Breaking');
insert into tag (id, tag_name) values (NULL, 'Worldbuilding');
insert into tag (id, tag_name) values (NULL, 'Wrestling');
insert into tag (id, tag_name) values (NULL, 'Writing');
insert into tag (id, tag_name) values (NULL, 'Writing Music');
insert into tag (id, tag_name) values (NULL, 'Writing Songs');
insert into tag (id, tag_name) values (NULL, 'Yo-yoing');
insert into tag (id, tag_name) values (NULL, 'Yoga');
insert into tag (id, tag_name) values (NULL, 'YoYo');
insert into tag (id, tag_name) values (NULL, 'Ziplining');
insert into tag (id, tag_name) values (NULL, 'Zumba');
